### ISSUE TITLE
播放 mv/视频接口没有

### ISSUE THREAD

**Issue by ohongyangf** [wwh1004/NeteaseCloudMusicApi#1]
尝试用到“获取“视频播放地址”接口也返回是400错误，
尝试用到“获取”mv 地址”接口也返回是400错误。
请麻烦提供下 播放视频接口谢谢了

**Comment by wwh1004** [comment]
我刚才发现里面一个地址写错了，然后你传的id是不是 EC6675F9EB2394ACEC4A7B8E4948B5A2 这样的，如果是的话，nodejs版的似乎也返回400

**Comment by ohongyangf** [comment]
你好，能加你个QQ跟你请教下吗？我现在遇到的是按文档和源码看了没有播放 mv/视频接口，然后找的是
&nbsp; &nbsp; &nbsp; &nbsp; /// <summary&gt;
&nbsp; &nbsp; &nbsp; &nbsp; /// 获取视频播放地址
&nbsp; &nbsp; &nbsp; &nbsp; /// </summary&gt;
&nbsp; &nbsp; &nbsp; &nbsp; public static readonly CloudMusicApiProvider VideoUrl = new CloudMusicApiProvider("/video/url", HttpMethod.Post, q =&gt; "https://music.163.com/weapi/cloudvideo/playurl", new ParameterInfo[] {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; new ParameterInfo("ids") { KeyForwarding = "id", Transformer = JsonArrayTransformer },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; new ParameterInfo("resolution", ParameterType.Optional, "1080") { KeyForwarding = "res" }
&nbsp; &nbsp; &nbsp; &nbsp; }, BuildOptions("weapi"));

调用这接口尝试看下能不能刷新出播放次数。对的，我传的是视频ID。如你写的格式一样。
我QQ：517228263


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"文煌"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 晚上10:35
收件人:&nbsp;"wwh1004/NeteaseCloudMusicApi"<NeteaseCloudMusicApi@noreply.github.com&gt;;
抄送:&nbsp;"517228263"<517228263@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wwh1004/NeteaseCloudMusicApi] 播放 mv/视频接口没有 (#1)




我刚才发现里面一个地址写错了，然后你传的id是不是 EC6675F9EB2394ACEC4A7B8E4948B5A2 这样的，如果是的话，nodejs版的似乎也返回400

**Comment by wwh1004** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/447

这个是video id，你的应该用 VideoUrl 的那个字段 http://localhost:3000/video/url?id=EC6675F9EB2394ACEC4A7B8E4948B5A2

**Comment by ohongyangf** [comment]
嗯对的，现在这接口遇到些问题，请求/video/url，调用的是这接口访问https://music.163.com/weapi/cloudvideo/playurl，
调用示例：(isOk, json) = await api.RequestAsync(CloudMusicApiProviders.VideoUrl, new Dictionary<string, string&gt; { { "id", "95A3D4A16E9790752269D84FE3A9892E" } });
返回：400错误，麻烦帮检查下是接口的问题还是参数的问题。本人对爬取知识有限，需要你多指点下了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"文煌"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月20日(星期五) 下午5:23
收件人:&nbsp;"wwh1004/NeteaseCloudMusicApi"<NeteaseCloudMusicApi@noreply.github.com&gt;;
抄送:&nbsp;"517228263"<517228263@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wwh1004/NeteaseCloudMusicApi] 播放 mv/视频接口没有 (#1)




Binaryify/NeteaseCloudMusicApi#447
 
这个是video id，你的应该用 VideoUrl 的那个字段 http://localhost:3000/video/url?id=EC6675F9EB2394ACEC4A7B8E4948B5A2

**Comment by wwh1004** [comment]
你看看刚刚提交的，现在应该可以了

**Comment by ohongyangf** [comment]
还有个问题想请教下，我尝试请求“mv 地址”接口，请求返回时200，是成功了的，但是网页上刷新看到的，MV播放次数没有增加，这是什么情况呢？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"文煌"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月20日(星期五) 下午5:42
收件人:&nbsp;"wwh1004/NeteaseCloudMusicApi"<NeteaseCloudMusicApi@noreply.github.com&gt;;
抄送:&nbsp;"517228263"<517228263@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wwh1004/NeteaseCloudMusicApi] 播放 mv/视频接口没有 (#1)




你看看刚刚提交的，现在应该可以了

**Comment by wwh1004** [comment]
这个我就不清楚了，我只是把原项目翻译成c#了，这个你可能要到原项目那里开issue问问
https://github.com/Binaryify/NeteaseCloudMusicApi/issues

**Comment by ohongyangf** [comment]
好的感谢，大哥。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"文煌"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月20日(星期五) 下午5:54
收件人:&nbsp;"wwh1004/NeteaseCloudMusicApi"<NeteaseCloudMusicApi@noreply.github.com&gt;;
抄送:&nbsp;"517228263"<517228263@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wwh1004/NeteaseCloudMusicApi] 播放 mv/视频接口没有 (#1)




这个我就不清楚了，我只是把原项目翻译成c#了，这个你可能要到原项目那里开issue问问
 https://github.com/Binaryify/NeteaseCloudMusicApi/issues
