### ISSUE TITLE
在二维码登录等接口的Code会被判断为失败

### ISSUE THREAD

**Issue by kengwang** [wwh1004/NeteaseCloudMusicApi#10]
在调用二维码状态检测 `/login/qr/check` 时,code返回不为200
而是 80x  会被 `IsSuccess` 给判断为返回失败
Refers To: https://github.com/wwh1004/NeteaseCloudMusicApi/blob/7b0c2bfb3ecd0dc1a028af2367f97b3b01d5149f/NeteaseCloudMusicApi/CloudMusicApi.cs#L111

**Comment by kengwang** [comment]
我是这样改的: https://github.com/kengwang/NeteaseCloudMusicApi/commit/15f567d9b4df6a361cc7f95de1fe795958e22c43
可能有不妥

**Comment by wwh1004** [comment]
好久没管这个项目了。上游项目更新挺快的，之前看的时候代码格式也很乱，不好写工具统一生成，不想继续更新了。就放着不动吧。

**Comment by kengwang** [comment]
> 好久没管这个项目了。上游项目更新挺快的，之前看的时候代码格式也很乱，不好写工具统一生成，不想继续更新了。就放着不动吧。

我也只能在我那个分支里面手动更新了 🤣
