### ISSUE TITLE
求未编译的dll，仅学习参考

### ISSUE THREAD

**Issue by huiji1** [wwh1004/NeteaseCloudMusicApi#3]

**Comment by wwh1004** [comment]
不是开源的吗，代码都在这里啊

**Comment by huiji1** [comment]
账号ID： 119412879
账号昵称： 我可以喜欢你吗-

pplicationException: 获取歌曲详情失败： {
  "code": 502,
  "msg": "Type: \r\nSystem.UriFormatException\r\nMessage: \r\nInvalid URI: The Uri string is too long.\r\nSource: \r\nSystem.Private.Uri\r\nStackTrace: \r\n   at System.UriHelper.EscapeString(String input, Int32 start, Int32 end, Char[] dest, Int32& destPos, Boolean isUriString, Char force1, Char force2, Char rsvd)\r\n   at System.Uri.EscapeDataString(String stringToEscape)\r\n   at System.Extensions.HttpExtensions.<>c.<ToQueryString>b__0_0(KeyValuePair`2 t) in C:\\projects\\neteasecloudmusicapi\\NeteaseCloudMusicApi\\System\\Extensions\\HttpExtensions.cs:line 10\r\n   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()\r\n   at System.String.Join(String separator, IEnumerable`1 values)\r\n   at System.Extensions.HttpExtensions.ToQueryString(IEnumerable`1 queries) in C:\\projects\\neteasecloudmusicapi\\NeteaseCloudMusicApi\\System\\Extensions\\HttpExtensions.cs:line 10\r\n   at NeteaseCloudMusicApi.util.request.createRequest(HttpClient client, HttpMethod method, String url, IEnumerable`1 data_, options options) in C:\\projects\\neteasecloudmusicapi\\NeteaseCloudMusicApi\\util\\request.cs:line 134\r\nTargetSite: \r\nChar[] EscapeString(System.String, Int32, Int32, Char[], Int32 ByRef, Boolean, Char, Char, Char)\r\n----------------------------------------\r\n"

**Comment by wwh1004** [comment]
你参数肯定传错了，你代码发一下

**Comment by huiji1** [comment]
接口是SongDetail ，传值是uid（119412879）

**Comment by wwh1004** [comment]
你调试看看，源码就在这里

**Comment by huiji1** [comment]
应该是我这个歌单的问题。

**Comment by wwh1004** [comment]
你的参数是错的啊。。你看下源码定义，或者nodejs版的那个文档。猜一个参数去传肯定报错的

**Comment by wwh1004** [comment]
如果有问题开一个新issue，你问的问题和现在这个issue没太大关系，不方便管理

**Comment by huiji1** [comment]
嗯

**Comment by wwh1004** [comment]
var z=	await		api.RequestAsync(CloudMusicApiProviders.SongDetail, new Dictionary<string, string>() { ["ids"] = "119412879" });

**Comment by huiji1** [comment]
大佬，请问下 (isOk, json) = await api.RequestAsync(CloudMusicApiProviders.UserPlaylist, new Dictionary<string, string> { { "uid", uidd } });   

(isOk, json) 在c#中是什么写法，(isOk, json)接受返回来的参数，一般的方法不就是返回一个的吗？

**Comment by wwh1004** [comment]
值元组语法糖和解构语法糖

**Comment by huiji1** [comment]
刚才出错的问题我想到了，首先是获取我喜欢的音乐歌单，歌单中可能有些音乐的id是不可用的，所以出错

**Comment by huiji1** [comment]
> 值元组语法糖和解构语法糖

膜拜大佬
