### ISSUE TITLE
api的私信和更新用户

### ISSUE THREAD

**Issue by ykl2011** [wwh1004/NeteaseCloudMusicApi#4]
使用api发送私信和更新用户信息返回的json都是 illegal request , code 403. 有办法解决吗？谢谢大神。

会不会是因为checktoken的因素？

{"nickname":"stevejob2025","signature":"halo!","gender":"1","avatarImgId":"0","province":"640000","city":"640100","birthday":"665424000000","checkToken":"9ca17ae2e6ffcda170e2e6eeb5ef6aabbb99d2ee41e9968ea3c85a928e8abaf560a988b7ccc75c82b2a48fae2af0feaec3b92aa9a9a7ccb43ca68fa9b9d95f879f9ba7d14ba1f1898dcb73e992faa9fc70abaaee9e","csrf_token":"1aaed7e018c144a79c047d7e3b953379"}

![image](https://user-images.githubusercontent.com/7509625/86320204-eb635e00-bc68-11ea-9191-094a3776a0ca.png)

**Comment by wwh1004** [comment]
没看懂你的代码...你是不是改过了我的api，还是你自己写了

**Comment by ykl2011** [comment]
> 没看懂你的代码...你是不是改过了我的api，还是你自己写了

 是自己写，但是api还是使用你的。JObject jonf = await 发送命令(api, API操作类型.修改昵称, dcgz11) 这里会引用以下的api。 

		public static readonly CloudMusicApiProvider UserUpdate = new CloudMusicApiProvider("/user/update", HttpMethod.Post, q => "https://music.163.com/weapi/user/profile/update", new ParameterInfo[] {
			new ParameterInfo("nickname"),
			new ParameterInfo("signature"),
			new ParameterInfo("gender"),
			new ParameterInfo("avatarImgId", ParameterType.Constant, "0"),
			new ParameterInfo("province"),
			new ParameterInfo("city"),
			new ParameterInfo("birthday")		
		}, BuildOptions("weapi"));

**Comment by wwh1004** [comment]
用我写的会不会出问题？

**Comment by ykl2011** [comment]
> 用我写的会不会出问题？

也是一样....测试很多次了 =(

**Comment by wwh1004** [comment]
那api要更新下，你去原项目看看，我最近没时间更新，和原项目落后好几个版本了

**Comment by wwh1004** [comment]
然后这个api要登录的，你登录没？

**Comment by ykl2011** [comment]
已经登入了，亲·。

**Comment by ykl2011** [comment]
> 那api要更新下，你去原项目看看，我最近没时间更新，和原项目落后好几个版本了

感谢大神！么么哒！
